#! /usr/bin/expect -f

set arg1 [lindex $argv 0]
set arg2 [lindex $argv 1]
send $arg1\n
send $arg2\n

spawn scp -P 8022 "$arg1" "$arg2" 

expect {
"password:" {
    send "@Qwer1234\r"
    expect "*\r"
    expect "\r"
}
"yes/no)?" {
    send "yes\r"
    sleep 2
    exp_continue
}
timeout {
    puts "\nError: timed out.\n"
    exit
}
}
